#!/usr/bin/with-contenv sh
if [ ! -d /var/www/drupal/web/sites/all/modules/civicrm ] 
then 
    wget -q https://download.civicrm.org/civicrm-${CIVICRM_VERSION}-drupal.tar.gz -O /tmp/civicrm.tgz
    wget -q https://download.civicrm.org/civicrm-${CIVICRM_VERSION}-l10n.tar.gz -O /tmp/civicrm-l10n.tgz
    wget -q https://raw.githubusercontent.com/civicrm/civicrm-drupal/7.x-master/drush/civicrm.drush.inc -O /root/.drush/civicrm.drush.inc 
    wget https://github.com/civicrm/org.civicrm.shoreditch/archive/v0.1-alpha31.zip -O /tmp/ext.zip 
    cd /var/www/drupal
    vendor/bin/drush cache-clear drush

    while ! $( nc -vz ${DATABASE_HOST} ${DATABASE_PORT} ) ;
    do
        sleep 1
    done
   
    echo "> Installing CiviCRM"

    vendor/bin/drush civicrm-install \
        --site_url=${TRUSTED_HOST} \
        --dbhost=${DATABASE_HOST}:${DATABASE_PORT} \
        --dbname=${CIVICRM_DB_NAME} \
        --dbuser=${CIVICRM_DB_USERNAME} \
        --dbpass=${CIVICRM_DB_PASSWORD} \
        --tarfile=/tmp/civicrm.tgz \
        --lang=fr_FR \
        --langtarfile=/tmp/civicrm-l10n.tgz \
        --ssl=off
    unzip /tmp/ext.zip -d /var/www/drupal/web/sites/default/files/civicrm/ext/
    rm /tmp/* -R || true

    echo "> Installing CiviCRM Extensions"
    vendor/bin/drush civicrm-ext-install org.civicrm.api4
    vendor/bin/drush -y pm-enable civicrm_contact_ref civicrmtheme civicrm_engage civicrm_group_roles civicrm_member_roles
    
    chown nginx:nginx /var/www/drupal/web/sites/default/files/civicrm/ext/ -R
    vendor/bin/drush cache-clear all
    vendor/bin/drush civicrm-ext-install org.civicrm.shoreditch

    echo ">>> Setting up Shoreditch"
    vendor/bin/drush cvapi Setting.create customCSSURL="[civicrm.files]/ext/org.civicrm.shoreditch-0.1-alpha31/css/custom-civicrm.css"

    chown nginx:nginx web -R
fi

echo "0" >/tmp/civicrm
