#!/usr/bin/with-contenv sh

fail(){
    echo "[ Failed ]"
    echo "1" > /tmp/civicrm
    exit 1
}

success(){
    echo "[ Success ]"
    echo "0" > /tmp/civicrm
    exit 0
}

wait_db(){
    echo ">>> Waiting for database to be ready"
    while ! $( nc -vz ${DATABASE_HOST} ${DATABASE_PORT} )
    do
            sleep 1
    done
}

run(){
    eval "su - nginx -s /bin/ash -c 'cd /var/www/drupal/ && "$@"'" 
    return $? 
}

if [ ! -d /var/www/drupal/web/sites/all/modules/civicrm ] 
then 
    wait_db
   
    echo ">>> Installing CiviCRM"
    cp /opt/ressources/civicrm.drush.inc /var/www/drupal/drush/civicrm.drush.inc
    run vendor/bin/drush cc all || fail
    chmod u+w /var/www/drupal/web/sites/default 
    run vendor/bin/drush civicrm-install \
        --site_url=${TRUSTED_HOST} \
        --dbhost=${DATABASE_HOST}:${DATABASE_PORT} \
        --dbname=${CIVICRM_DB_NAME} \
        --dbuser=${CIVICRM_DB_USERNAME} \
        --dbpass=${CIVICRM_DB_PASSWORD} \
        --tarfile=/opt/ressources/civicrm.tgz \
        --lang=fr_FR \
        --langtarfile=/opt/ressources/civicrm-l10n.tgz \
        --ssl=${USE_HTTPS} || fail
    
    run unzip -q /opt/ressources/shoreditch.zip -d /var/www/drupal/web/sites/all/modules/civicrm/ext/ || fail

    echo ">>> Installing Drupal Extensions"
    run cp /opt/ressources/betterlogin.tar.gz /var/www/drupal/web/sites/all/modules/ 
    run tar -xzf /var/www/drupal/web/sites/all/modules/betterlogin.tar.gz -C /var/www/drupal/web/sites/all/modules/ 
    run rm  /var/www/drupal/web/sites/all/modules/betterlogin.tar.gz 
    run vendor/bin/drush cc all || fail
    run vendor/bin/drush -y pm-enable civicrm_contact_ref civicrmtheme civicrm_engage civicrm_group_roles civicrm_member_roles betterlogin || fail

    echo ">>> Installing CiviCRM Extensions"
    run vendor/bin/drush civicrm-ext-install org.civicrm.shoreditch || fail
    run vendor/bin/drush cvapi Setting.create customCSSURL="[civicrm.root]/ext/org.civicrm.shoreditch-0.1-alpha31/css/custom-civicrm.css" || fail

    echo ">>> Setting up Drupal and Civicrm Themes"
    run vendor/bin/drush vset civicrmtheme_theme_admin seven
    run vendor/bin/drush vset civicrmtheme_theme_public seven
    run vendor/bin/drush vset admin_theme seven

    echo ">>> Setting up Drupal Homepage "
    run vendor/bin/drush vset site_frontpage civicrm/dashboard
    run vendor/bin/drush vset site_403 user/login

    echo ">>> Enabling Civicrm Memcached"
    sed -i "s/ArrayCache/Memcached/g" /var/www/drupal/web/sites/default/civicrm.settings.php
fi

success